import fixture from "./response-fixture.json";
import {parseResponseHistory} from "./response-monitoring";

// Synthetic data, generated by the actual estimator. Explicit demonstration only.
export const responseFixture = parseResponseHistory(fixture);
