"use client";
import { WEEKDAYS } from "../lib/planning-profile";
import { availabilityMode, trainingDays, COMPONENTS, type Component, type ManagementProfile, type PlanningControls, type VolumeHistory } from "../lib/training-management";

export const SPORT_NAMES: Record<string, string> = { Run: "Бягане", NordicSki: "Ски бягане", RollerSki: "Ролкови ски", WeightTraining: "Сила", TrailRun: "Планинско бягане", Walk: "Ходене", Ride: "Колоездене", VirtualRun: "Бягаща пътека" };
const hours = (v: number) => (v/60).toLocaleString("bg-BG", {maximumFractionDigits: 1});
export function HistoryVolume({ history, selected }: { history?: VolumeHistory | null; selected?: string[] }) {
  if (!history || !history.covered_days) return <p className="management-notice">Още няма достатъчна внесена история. Обнови активностите или въведи обемите за четирите седмици.</p>;
  return <section className="management-history"><h3>Реалната история · последни 28 дни</h3><p><strong>{hours(history.all_sports_weekly_minutes)} часа / седмица общо</strong> · {history.covered_days} покрити дни{history.as_of ? ` · анализ до ${history.as_of}` : ""}</p>{history.history_policy&&!history.history_policy.usable&&<p className="management-notice">Кратка или прекъсната история: {history.history_policy.reference_days} дни в текущия участък. Засега предложенията са ограничени.</p>}{history.history_policy?.trimmed_before_break&&<p>След прекъсването началната база използва само новия участък.</p>}<div className="management-zone-legend">{Object.entries(history.by_sport_weekly_minutes).map(([sport, minutes]) => <span key={sport}>{SPORT_NAMES[sport] ?? sport}: <strong>{hours(minutes)} ч</strong>{selected && !selected.includes(sport) ? " · друго средство" : ""}</span>)}</div><p className="management-muted">Историята е началната основа; целите 7/40 управляват товара по зони. Дозата и опитът се проверяват отделно за действителното средство; скорост и капацитет не се пренасят между спортове.</p></section>;
}
function ZoneChoices({ value, onChange, label }: { value: Component[]; onChange: (v: Component[]) => void; label: string }) {
  return <div className="management-zone-legend" role="group" aria-label={label}>{COMPONENTS.map(z => <label key={z} className="management-check"><input type="checkbox" checked={value.includes(z)} onChange={e => onChange(e.target.checked ? [...value,z] : value.filter(x => x!==z))}/>{z}</label>)}</div>;
}
export function PlanningControlsEditor({ profile, onChange, stage, history }: { profile: ManagementProfile; onChange: (p: ManagementProfile) => void; stage: "days" | "cycles"; today: string; history?: VolumeHistory | null }) {
  const c = profile.planning_controls!;
  const mode = availabilityMode(profile), selectedDays = trainingDays(profile);
  const slots = selectedDays.reduce((sum,i)=>sum+(c.sessions_by_day?.[i]??3),0);
  const setDays = (selected: number[]) => onChange({...profile, training_days: selected, planning_controls: {...c,
    threshold_days: (c.threshold_days??[]).filter(i=>selected.includes(i)), double_threshold_days: (c.double_threshold_days??[]).filter(i=>selected.includes(i)),
    intensity_days: c.intensity_days.filter(i => selected.includes(i)), strength_days: c.strength_days.filter(i => selected.includes(i)),
    long_session_day: c.long_session_day !== null && selected.includes(c.long_session_day) ? c.long_session_day : null}});
  const update = <K extends keyof PlanningControls>(key: K, value: PlanningControls[K]) => onChange({...profile, planning_controls: {...c,[key]:value}});
  const setAvailability = (minutes: number[]) => onChange({...profile, availability_mode: "MANUAL", training_days: minutes.flatMap((v,i)=>v>0?[i]:[]), available_minutes: minutes, planning_controls: {...c,
    threshold_days: (c.threshold_days??[]).filter(i=>minutes[i]>0), double_threshold_days: (c.double_threshold_days??[]).filter(i=>minutes[i]>0),
    intensity_days: c.intensity_days.filter(i => minutes[i] > 0), strength_days: c.strength_days.filter(i => minutes[i] > 0),
    long_session_day: c.long_session_day !== null && minutes[c.long_session_day] > 0 ? c.long_session_day : null}});
  const days = (key: "intensity_days"|"strength_days"|"threshold_days", title: string) => <fieldset><legend>{title} · без избор = автоматично</legend><div className="management-week-grid">{WEEKDAYS.map((d,i)=><label key={d} className="management-check"><input type="checkbox" disabled={!selectedDays.includes(i)} checked={(c[key]??[]).includes(i)} onChange={e=>update(key,e.target.checked?[...(c[key]??[]),i]:(c[key]??[]).filter(x=>x!==i))}/>{d}</label>)}</div></fieldset>;
  if(stage==="days") return <><h2>2. Дни, средства и обем</h2><HistoryVolume history={history} selected={[...c.training_sports,...(profile.strength_enabled?["WeightTraining"]:[])]}/>
    <h3>Кои средства да използва програмата?</h3><div className="management-zone-legend">{(["Run", ...(profile.sport==="NordicSki"?["NordicSki","RollerSki"]:[])] as ManagementProfile["actual_sport"][]).map(s=><label key={s} className="management-check"><input type="checkbox" checked={c.training_sports.includes(s)} disabled={s===profile.actual_sport} onChange={e=>update("training_sports",e.target.checked?[...c.training_sports,s]:c.training_sports.filter(x=>x!==s))}/>{SPORT_NAMES[s]}</label>)}</div>
    <h3>Обемът следва историята и 7/40</h3><label>Как задаваме времето?<select value={mode} onChange={e=>onChange({...profile,availability_mode:e.target.value as "AUTO_HISTORY"|"MANUAL",training_days:selectedDays,available_minutes:profile.available_minutes.map((v,i)=>selectedDays.includes(i)?(v||60):0)})}><option value="AUTO_HISTORY">Автоматично от историята и целите 7/40</option><option value="MANUAL">Имам ограничения във времето</option></select></label>
    <p className="management-muted">Историята е началната база. 7/40 определя товара по зони; методът и готовността определят конкретните тренировки. Няма предварителен лимит 6,5 часа.</p>
    <h3>Тренировъчни дни · задължително</h3><p className="management-muted">Отметни дните, в които можеш да тренираш. Разрешен ден не означава задължителна тренировка.</p><div className="management-week-grid">{WEEKDAYS.map((d,i)=><div key={d}><label className="management-check"><input aria-label={`${d}: тренировъчен ден`} type="checkbox" checked={selectedDays.includes(i)} onChange={e=>{const selected=e.target.checked?[...selectedDays,i]:selectedDays.filter(v=>v!==i);if(mode==="MANUAL")setAvailability(profile.available_minutes.map((v,j)=>j===i?(e.target.checked?60:0):v));else setDays(selected);}}/>{d}</label>{mode==="MANUAL"&&<input aria-label={`${d}, налични минути`} type="number" min="0" max="360" step="5" value={selectedDays.includes(i)?profile.available_minutes[i]:0} onChange={e=>setAvailability(profile.available_minutes.map((v,j)=>i===j?Number(e.target.value):v))}/>}</div>)}</div>
    {mode==="MANUAL"&&<p><strong>Налично време: {hours(profile.available_minutes.reduce((sum,v,i)=>sum+(selectedDays.includes(i)?v:0),0))} ч / седмица.</strong> Това е твой лимит, а не цел за запълване.</p>}
    <details><summary>Кога историята е достатъчна?</summary><p>Поне 10 покрити календарни дни. Потвърдените почивни дни участват; липсващите данни не се приемат за почивка. След голямо прекъсване използваме новия участък, когато натрупа поне 10 дни.</p><label>Голямо прекъсване · последователни дни<input type="number" min="5" max="14" value={c.history_gap_days??10} onChange={e=>update("history_gap_days",Number(e.target.value))}/></label><p>Начално треньорско правило, подлежащо на настройка. Кратката или прекъсната история допуска само ограничени леки предложения.</p></details>
    {days("intensity_days","Дни за ключови аеробни и интервални тренировки")}{days("strength_days","Дни за сила")}
    <div className="management-form-grid"><label>Ден за дълга тренировка<select value={c.long_session_day??""} onChange={e=>update("long_session_day",e.target.value===""?null:Number(e.target.value))}><option value="">Автоматично</option>{WEEKDAYS.map((d,i)=><option key={d} value={i} disabled={!selectedDays.includes(i)}>{d}</option>)}</select></label><label>Максимум сесии за 7 дни<input type="number" min="1" max="21" value={c.sessions_per_week} onChange={e=>update("sessions_per_week",Number(e.target.value))}/></label><label>Максимум интензивни сесии<input type="number" min="0" max="8" value={profile.max_key_sessions_per_week} onChange={e=>onChange({...profile,max_key_sessions_per_week:Number(e.target.value)})}/></label><label>Максимум силови сесии<input type="number" min="0" max="3" value={c.max_strength_sessions} onChange={e=>update("max_strength_sessions",Number(e.target.value))}/></label><label>Максимум общо време за 7 дни, часове · по желание<input type="number" min=".1" max="42" step=".1" placeholder="Без седмичен таван" aria-describedby="weekly-time-limit-help" value={c.weekly_target_hours??""} onChange={e=>update("weekly_target_hours",e.target.value===""?null:Number(e.target.value))}/></label></div>
    <p id="weekly-time-limit-help" className="management-muted">Празно поле = без отделен седмичен таван. Стойност 1 означава максимум 1 час общо, не добавяне на 1 час. Изпълнените тренировки в периода също се броят. За по-кратък проект таванът се намалява пропорционално на дните.</p>
    {c.weekly_target_hours != null && <p className="management-notice" role="status">Задаваш максимум <strong>{hours(c.weekly_target_hours*60)} часа общо за 7 дни</strong>.{history && c.weekly_target_hours*60 < history.all_sports_weekly_minutes && " Това е под досегашния общ седмичен обем."} <button type="button" onClick={()=>update("weekly_target_hours",null)}>Премахни седмичния таван</button></p>}
    <label>Разпределение на сесиите<select value={c.sessions_by_day==null?"AUTO":"MANUAL"} onChange={e=>update("sessions_by_day",e.target.value==="AUTO"?null:[0,1,2,3,4,5,6].map(i=>selectedDays.includes(i)?((c.double_threshold_days??[]).includes(i)?2:1):0))}><option value="AUTO">Автоматично · до 3 на тренировъчен ден</option><option value="MANUAL">Задавам максимум за всеки ден</option></select></label>
    {c.sessions_by_day&&<div className="management-week-grid">{WEEKDAYS.map((d,i)=><label key={d}>{d}<input aria-label={d+": максимум сесии"} type="number" min="0" max="3" disabled={!selectedDays.includes(i)} value={selectedDays.includes(i)?c.sessions_by_day![i]:0} onChange={e=>update("sessions_by_day",c.sessions_by_day!.map((v,j)=>i===j?Number(e.target.value):v))}/></label>)}</div>}
    <p role="status">Избраните дни позволяват до <strong>{Math.min(c.sessions_per_week,slots)} сесии седмично</strong>.{slots<c.sessions_per_week&&` Седмичният максимум е ${c.sessions_per_week}, но ограниченията по дни позволяват само ${slots}. Увеличи бройките по дни или избери автоматично разпределение.`}</p>
    <h3>Прагова работа</h3><label>Вид прагова тренировка<select value={c.threshold_method??"AUTO"} onChange={e=>update("threshold_method",e.target.value as PlanningControls["threshold_method"])}><option value="AUTO">Автоматичен избор</option><option value="CONTINUOUS">Непрекъсната</option><option value="INTERVALS">На интервали</option></select></label>{days("threshold_days","Дни за прагова работа")}
    <details open={(c.double_threshold_days??[]).length>0}><summary>Двоен праг · по желание</summary><p>Две прагови сесии в един ден с обща работна доза и отделни загрявки. Изисква попълнени възраст и стаж. Не се планира автоматично при вработване, тейпър или недостатъчна готовност.</p><div className="management-week-grid">{WEEKDAYS.map((d,i)=><label key={d} className="management-check"><input type="checkbox" disabled={!selectedDays.includes(i)||(!(c.double_threshold_days??[]).includes(i)&&(c.double_threshold_days??[]).length>=3)} checked={(c.double_threshold_days??[]).includes(i)} onChange={e=>{const selected=e.target.checked?[...(c.double_threshold_days??[]),i]:(c.double_threshold_days??[]).filter(v=>v!==i);onChange({...profile,max_key_sessions_per_week:Math.max(profile.max_key_sessions_per_week,2*selected.length),planning_controls:{...c,double_threshold_days:selected,sessions_per_week:Math.max(c.sessions_per_week,2*selected.length),sessions_by_day:c.sessions_by_day?.map((v,j)=>selected.includes(j)?Math.max(2,v):v)??null}});}}/>{d}</label>)}</div><p className="management-muted">Всяка от двете сесии се брои към седмичния интензивен лимит. Изборът на ден се проверява спрямо бюджета.</p><div className="management-zone-legend">{(["Z3","Z4"] as const).map(z=><label key={z} className="management-check"><input type="checkbox" checked={(c.double_threshold_components??["Z3"]).includes(z)} onChange={e=>update("double_threshold_components",e.target.checked?[...(c.double_threshold_components??["Z3"]),z]:(c.double_threshold_components??["Z3"]).filter(v=>v!==z))}/>{z}</label>)}</div><p>Z4 участва само с индивидуален интервален профил с цел „Прагова работа“ в стъпка 4. Интервалите за аеробна мощност не се превръщат автоматично в прагова тренировка.</p></details>
    <p className="management-muted">До 21 сесии седмично и 3 дневно. Това са максимуми. Времето и 7/40 бюджетът са общи за деня; допълнителните сесии не добавят нова пълна изграждаща доза. Recovery прогнозира сумарния дневен товар.</p>
  </>;
  return <><h2>3. Мезоцикли, акценти и натоварване</h2><p>Автоматичните акценти се редуват по мезоцикли според периода и състезателното време. През натоварващите седмици остават постоянни. При разтоварване водещите компоненти се намаляват; възможна е поддържаща работа по един по-слабо натоварен компонент, ако 7/40 и готовността го позволяват. Можеш да зададеш постоянни акценти или отделни блокове по дати.</p><div className="management-form-grid"><label>Начало на мезоцикличната вълна<input type="date" value={c.mesocycle_anchor??profile.program_start} onChange={e=>update("mesocycle_anchor",e.target.value)}/></label><label>Акценти<select value={c.accent_mode} onChange={e=>update("accent_mode",e.target.value as PlanningControls["accent_mode"])}><option value="AUTO">Автоматично по мезоцикли</option><option value="MANUAL">Моят избор</option><option value="HYBRID">Моят избор + автоматично допълване</option></select></label>{c.accent_mode==="AUTO"?<label>Максимум автоматични приоритети<select value={c.automatic_focus_count??3} onChange={e=>update("automatic_focus_count",Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label>:<><label>Брой акценти<input type="number" min="1" max="6" value={c.accent_limit} onChange={e=>update("accent_limit",Number(e.target.value))}/></label><label>Целеви 7/40 за акцент<input type="number" min=".5" max="2" step=".01" value={c.accent_index} onChange={e=>update("accent_index",Number(e.target.value))}/></label></>}<label>Целеви 7/40 за поддържане<input type="number" min=".5" max="1.2" step=".01" value={c.maintenance_index} onChange={e=>update("maintenance_index",Number(e.target.value))}/></label><label>Седмици в мезоцикъла<select value={c.wave.length} onChange={e=>{const n=Number(e.target.value);update("wave",Array.from({length:n},(_,i)=>i===n-1?.78:[.96,1.04,1.1,1.1,1.1][i]));}}>{[2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
    {c.accent_mode==="AUTO"&&<><p>Приоритетите са подредени: водещ, втори и трети с леко развитие. При три автоматични приоритета общата подготовка започва със Z1–Z3–сила, следвани от Z2–Z4–Z5. При по-малко приоритети ротацията продължава през компонентите; кратък период може да не осигури акцент за всеки. Изключената сила не участва.</p><p>В началото на специалната подготовка водеща е състезателната зона, със съседна зона и сила, когато е включена. В последния подходящ специалноподготвителен мезоцикъл и в предсъстезателния период приоритет получават състезателната зона и близките до нея зони. При Z4 това са Z4–Z3–Z5; при крайна зона се използват двете най-близки налични зони. В състезателния период акцентът остава състезателната зона. При вработване всички включени компоненти имат цел 1,2, с отделна проверка на дозата.</p><div className="management-form-grid">{(["ranked_indices","shock_indices"] as const).map(key=><fieldset key={key}><legend>{key==="ranked_indices"?"Обичайни цели 7/40":"Цели за ударен микроцикъл"}</legend>{(c[key]??(key==="ranked_indices"?[1.6,1.5,1.2]:[2,1.8,1.6])).map((v,i)=><label key={i}>{["Водещ","Втори","Трети"][i]}<input aria-label={`${key==="ranked_indices"?"Обичаен":"Ударен"} ${["водещ","втори","трети"][i]} приоритет`} type="number" min="1" max="2" step=".05" value={v} onChange={e=>update(key,(c[key]??(key==="ranked_indices"?[1.6,1.5,1.2]:[2,1.8,1.6])).map((n,j)=>i===j?Number(e.target.value):n))}/></label>)}</fieldset>)}</div><p>По един ударен микроцикъл се предвижда в специалния и предсъстезателния период, когато има цяла седмица и последващо разтоварване. Изпълнението зависи от готовността и наличния обем.</p></>}
    {c.accent_mode!=="AUTO"&&<ZoneChoices label="Постоянни акценти" value={c.accents} onChange={v=>update("accents",v)}/>}
    <h3>Вълна на натоварване</h3><div className="management-week-grid">{c.wave.map((v,i)=><label key={i}>Седмица {i+1}{i===c.wave.length-1?" · разтоварване":""}<input aria-label={`Коефициент седмица ${i+1}`} type="number" min=".5" max={i===c.wave.length-1?".99":"1.5"} step=".01" value={v} onChange={e=>update("wave",c.wave.map((x,j)=>i===j?Number(e.target.value):x))}/></label>)}</div><p className="management-muted">Компонентните цели се умножават по седмичната вълна, с таван 2. Разтоварването има отделен намален бюджет и избира най-много един по-слабо натоварен компонент. Това са редактиращи се треньорски цели, не универсални граници за безопасност. Вработването и тейпърът имат отделни ограничения.</p>
    <p>Мезоциклите, стресовите блокове и акцентите по дати се задават в <a href="#planning-calendar">общия календар по-долу</a>. Там виждаш и разтоварването след тях.</p>
  </>;
}
