"use client";
import { SymptomNotice } from "./symptom-notice";
import { useState } from "react";
import { SaveForm } from "./response-save-form";
import { StressOverview } from "./stress-overview";
import { optionalNumber } from "../lib/body-observations";
import { BodyObservations } from "./body-observations";
import Link from "next/link";
import { FIELD_LABELS, REASONS, PHASES, type ResponseHistory, type ResponseDay, type Session } from "../lib/response-monitoring";

const fmt = (v:number|null|undefined) => v==null?"—":v.toLocaleString("bg-BG",{maximumFractionDigits:1});
const labelDate = (s:string) => s.slice(8,10)+"."+s.slice(5,7);
const anchorLabels:Record<string,string[]> = {
  sleep_quality:["Много добър","Добър","Среден","Лош","Много лош"],fatigue:["Без умора","Лека","Умерена","Силна","Много силна"],
  soreness:["Няма","Лека","Умерена","Силна","Много силна"],stress:["Много нисък","Нисък","Умерен","Висок","Много висок"],
  motivation:["Много мотивиран","Мотивиран","Средно","Слабо мотивиран","Без мотивация"],competition_motivation:["Много силно","Силно","Средно","Слабо","Липсва"]};


function DailyForm({day,today,canReport}:{day:ResponseDay;today:string;canReport:boolean}) {
  const report=day.daily_report;
  return <SaveForm key={`${day.day}:${day.daily_revision}`} kind="daily" disabled={!canReport} build={f=>({
    day:day.day,observed_at:report?.observed_at??(day.day===today?new Date().toISOString():null),
    ...Object.fromEntries(Object.keys(FIELD_LABELS).map(k=>[k,optionalNumber(f,k)])),sleep_hours:optionalNumber(f,"sleep_hours"),pain_or_illness:f.get("pain_or_illness")==="on",note:String(f.get("note")||""),expected_revision:day.daily_revision})}>
    <legend>Сутрешна оценка · {labelDate(day.day)}</legend>
    <p>Отговорете според състоянието преди тренировката. Попълнете наличното. Празните отговори не се приемат за добро състояние.</p>
    <div className="response-fields">{Object.entries(FIELD_LABELS).map(([key,label])=><label key={key}>{label}<select name={key} defaultValue={report?.[key as keyof typeof report]==null?"":String(report[key as keyof typeof report])}><option value="">Избери…</option>{anchorLabels[key].map((text,i)=><option key={i} value={i+1}>{i+1} · {text}</option>)}</select></label>)}</div>
    <label>Продължителност на съня · часове<input type="number" name="sleep_hours" min="0" max="24" step="0.1" defaultValue={report?.sleep_hours??""} placeholder="По желание; иначе използваме данните от Intervals"/></label>
    <label className="response-check"><input type="checkbox" name="pain_or_illness" defaultChecked={report?.pain_or_illness}/>Имам болка или симптоми, които искам да обсъдя с треньора</label>
    <label>Бележка (по желание)<textarea name="note" maxLength={500} defaultValue={report?.note||""}/></label>
    {!canReport&&<p>Личната оценка се въвежда от спортиста.</p>}
  </SaveForm>;
}

function SessionForm({session,canReport}:{session:Session;canReport:boolean}) {
  return <details className="response-session"><summary><span>{labelDate(session.day)} · {session.name}</span><span>RPE {fmt(session.rpe)} · sRPE {fmt(session.srpe_load)}</span></summary>
    <p><Link href={`/activities/${session.activity_ref}`}>Отвори активността</Link> · Източник: {session.source==="ONFLOWS"?"onFlows":session.source==="INTERVALS"?"Intervals":"няма оценка"}</p>
    <SaveForm key={`${session.activity_ref}:${session.revision}`} kind="session" disabled={!canReport} build={f=>({activity_ref:session.activity_ref,rpe:optionalNumber(f,"rpe"),duration_minutes:Number(f.get("duration_minutes")),timing:f.get("timing")||"UNKNOWN",note:String(f.get("note")||""),planned_duration_minutes:optionalNumber(f,"planned_duration_minutes"),planned_speed_kmh:optionalNumber(f,"planned_speed_kmh"),executed_speed_kmh:optionalNumber(f,"executed_speed_kmh"),execution_comparable:f.get("execution_comparable")==="on",execution_reason:f.get("execution_reason")||"UNKNOWN",expected_revision:session.revision})}>
      <legend>Какво усилие изискваше цялата тренировка?</legend>
      <div className="response-fields"><label>Усилие RPE · 0–10<select name="rpe" defaultValue={session.rpe??""}><option value="">Избери…</option>{Array.from({length:11},(_,i)=><option value={i} key={i}>{i}{i===0?" · без усилие":i===3?" · умерено":i===5?" · тежко":i===10?" · максимално":""}</option>)}</select></label>
      <label>Цяла сесия, минути<input name="duration_minutes" type="number" min="0.1" max="1440" step="0.1" required defaultValue={session.duration_minutes??(session.suggested_duration_minutes?Math.round(session.suggested_duration_minutes*10)/10:"")}/></label>
      <label>Кога направихте оценката?<select name="timing" defaultValue={session.timing==="UNKNOWN"?"":session.timing}><option value="">Избери…</option><option value="IMMEDIATE">Непосредствено след края</option><option value="DELAYED">Около 10–60 минути след края</option><option value="NEXT_DAY">На следващия ден</option></select></label></div>
      <p>Продължителността включва почивките в тренировката. Проверете предложеното време. sRPE = RPE × минути; не се прибавя към пулсовото натоварване.</p>
      <details><summary>Съпостави с плана · по желание</summary><p>Сравнете една и съща част от тренировката. Уточнете причината за отклонението; време, условия и треньорско решение не се оценяват като умора.</p><div className="response-fields"><label>Планирана цяла сесия · минути<input name="planned_duration_minutes" type="number" min="0.1" max="1440" step="0.1" defaultValue={session.execution?.planned_duration_minutes??""}/></label><label>Планирана скорост · km/h<input name="planned_speed_kmh" type="number" min="0.01" max="150" step="0.01" defaultValue={session.execution?.planned_speed_kmh??""}/></label><label>Изпълнена скорост · km/h<input name="executed_speed_kmh" type="number" min="0.01" max="150" step="0.01" defaultValue={session.execution?.executed_speed_kmh??""}/></label><label>Изпълнение / причина<select name="execution_reason" defaultValue={session.execution?.execution_reason??"UNKNOWN"}>{Object.entries(REASONS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label className="response-check"><input name="execution_comparable" type="checkbox" defaultChecked={session.execution?.execution_comparable??false}/>Съпоставими условия, метод и част от тренировката</label></details>
      <label>Бележка<textarea name="note" maxLength={500} defaultValue={session.note}/></label>
    </SaveForm>
    <p>{session.expected_rpe==null?`Нужни са поне 3 предишни съпоставими сесии. Налични: ${session.comparable_count}.`:`Обичайно RPE при сходна работа: ${fmt(session.expected_rpe)}; днес: ${fmt(session.rpe)}.`}</p>
  </details>;
}

export function ResponseMonitoring({history,canReport,canEditPlan}:{history:ResponseHistory;canReport:boolean;canEditPlan:boolean}) {
  const [selected,setSelected]=useState(history.days.length-1);
  const [showTests,setShowTests]=useState(false);
  const day=history.days[Math.min(selected,history.days.length-1)];
  return <>
    {history.symptom_context?.hold_for_reported_illness_or_pain && <SymptomNotice day={history.symptom_context.latest_report_day}/>}
    <StressOverview history={history} selected={selected} onSelect={setSelected}/>
    {day&&<><section className="response-card" id="daily-report"><details open={!day.daily_report}><summary>Сутрешна оценка · {labelDate(day.day)}</summary><DailyForm day={day} today={history.today} canReport={canReport}/></details></section><details className="response-card stress-observations"><summary>Тегло и изследвания · {labelDate(day.day)}</summary><BodyObservations day={day} history={history} canReport={canReport} canEditPlan={canEditPlan}/></details></>}
    <section className="response-card"><details><summary>Възприето натоварване по активности</summary><p>Оценката от часовника се показва, когато Intervals я е предал. Поправката в onFlows има предимство и се пази при следващ импорт.</p>{history.sessions.length?history.sessions.slice().reverse().map(s=><SessionForm key={s.activity_ref} session={s} canReport={canReport}/>):<p>Няма активности в периода.</p>}</details></section>
    <section className="response-card"><details><summary>Реакция и отзвучаване по блокове</summary><p>Задайте предварително натоварващата част и края на разтоварването. Опорната база се фиксира при създаването. Започнал блок не се удължава със задна дата.</p><p>Обобщението тук следи субективното състояние. Проверявайте успоредно пулса, HRV и възприетото усилие в графиката. Прекъсване на оценките или ново покачване отменя потвърденото отзвучаване.</p>
      {history.blocks.map(b=><article key={b.entry_key} className="response-block"><strong>{PHASES[String(b.payload.phase)]} · {String(b.payload.start)} – {String(b.payload.recovery_end)}</strong><p>Край на натоварването: {String(b.payload.load_end)}. Пик: {fmt(b.summary?.peak_deviation)} лични отклонения; повишени дни: {b.summary?.elevated_days??0}; наблюдавани: {b.summary?.observed_days??0}/{b.summary?.tracked_days??0}.</p><p>{b.summary?.returned_on?`Наблюдавано връщане: ${b.summary.returned_on} (две последователни оценки).`:b.summary?.status==="IN_PROGRESS"?"Блокът продължава.":b.summary?.status==="REVIEW"?"Реакцията остава повишена в края на разтоварването.":"Недостатъчно данни за връщане към обичайното състояние."}</p></article>)}
      {canEditPlan&&<details><summary>Задай следващ блок за наблюдение</summary><SaveForm kind="block" build={f=>({start:f.get("start"),load_end:f.get("load_end"),recovery_end:f.get("recovery_end"),phase:f.get("phase"),components:f.getAll("components"),note:String(f.get("note")||""),expected_revision:0})}><legend>Контекст на блока</legend><p>Изграждащ блок за обучение: до 38 дни общо, включително поне 2 дни след натоварването. Запиши съпоставимия тест до 14 дни след разтоварването, докато цялата история е налична.</p><fieldset><legend>Компоненти · празно означава обща реакция</legend>{["Z1","Z2","Z3","Z4","Z5","STR"].map(z=><label key={z} className="response-check"><input name="components" type="checkbox" value={z}/>{z}</label>)}</fieldset><div className="response-fields"><label>Начало<input type="date" name="start" min={history.today} required/></label><label>Край на натоварващата част<input type="date" name="load_end" min={history.today} required/></label><label>Край на разтоварването<input type="date" name="recovery_end" min={history.today} required/></label><label>Фаза<select name="phase" defaultValue="BUILD">{Object.entries(PHASES).filter(([k])=>k!=="UNSPECIFIED").map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label>Бележка<textarea name="note" maxLength={500}/></label></SaveForm></details>}
    </details></section>
    <section className="response-card"><details><summary>Доброволни контролни тестове</summary><p>Използват се по преценка на треньора. При поне три предишни съпоставими резултата участват в оценката за деня на теста. Съпоставимите резултати могат да участват в управлението на прираста след завършен блок, когато то е включено в профила. Липсата им не доказва успешна адаптация.</p>
      {history.tests.map(t=><p key={t.entry_key}>{String(t.payload.day)} · {String(t.payload.protocol)} ({String(t.payload.protocol_version)}): <strong>{String(t.payload.value)} {String(t.payload.unit)}</strong> · {t.payload.comparable?"условията са отбелязани като съпоставими":"съпоставимостта не е потвърдена"}{t.payload.load_observation_status==="UNAVAILABLE"&&<span className="management-error"> · Липсва запазена пълна товарна история за свързания блок. Резултатът е записан, но няма основание за обучение от този блок.</span>}{t.payload.load_observation_status==="ARCHIVED"&&<span> · Използва се съхранената товарна история на блока.</span>}</p>)}
      {canEditPlan&&<><button type="button" className="action-button secondary" onClick={()=>setShowTests(!showTests)}>{showTests?"Скрий формата":"Добави резултат по избор"}</button>{showTests&&<SaveForm kind="test" build={f=>({day:f.get("day"),protocol:f.get("protocol"),protocol_version:f.get("protocol_version"),value:Number(f.get("value")),unit:f.get("unit"),direction:f.get("direction"),conditions:f.get("conditions"),comparable:f.get("comparable")==="on",components:f.getAll("components"),meaningful_change_percent:Number(f.get("meaningful_change_percent")||1),expected_revision:0})}><legend>Резултат и условия</legend><fieldset><legend>Компоненти · празно означава обща реакция</legend>{["Z1","Z2","Z3","Z4","Z5","STR"].map(z=><label key={z} className="response-check"><input name="components" type="checkbox" value={z}/>{z}</label>)}</fieldset><label>Минимална значима промяна, %<input name="meaningful_change_percent" type="number" min=".01" max="20" step=".01" defaultValue="1" required/></label><div className="response-fields"><label>Дата<input name="day" type="date" max={history.today} required/></label><label>Протокол<input name="protocol" minLength={3} maxLength={100} required/></label><label>Версия<input name="protocol_version" maxLength={32} required/></label><label>Стойност<input name="value" type="number" step="any" min="0.000001" required/></label><label>Мерна единица<input name="unit" maxLength={24} required/></label><label>Подобрение при<select name="direction"><option value="HIGHER">По-висока стойност</option><option value="LOWER">По-ниска стойност</option></select></label></div><label>Трасе, екипировка и условия<textarea name="conditions" minLength={3} maxLength={500} required/></label><label className="response-check"><input name="comparable" type="checkbox"/>Потвърждавам съпоставими условия</label></SaveForm>}</>}
    </details></section>
    <section className="response-card response-method"><details><summary>Как е настроена оценката</summary><p>Субективно състояние 35%, работоспособност 25%, пулс и HRV 15%, тегло 15%, биохимия 10%. Теглата са начални експертни настройки за тестване. Наличните показатели се претеглят отново; покритието показва колко от модела действително наблюдаваме.</p><p>Личната база е от предходните 28 дни, с поне 14 наблюдения. Сутрешният индекс изисква 4 измервания за 7 календарни дни. Лабораторните сравнения и тестовете изискват 3 предишни съпоставими дни. Старите измервания не се пренасят като днешни.</p><p>Ниската оценка не задейства увеличение на натоварването. Този етап подготвя наблюденията за самообучението; тренировъчният план и Recovery запазват текущата си логика.</p></details></section>
  </>;
}
